# Path to the twitter configuration file inside the container
path.config: /usr/share/logstash/config/twitter_logstash.conf

http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://es01:9200" ]

xpack.monitoring.enabled: true